src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;



    /**
     * @ORM\ManyToOne(targetEntity=User::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $token;

    /**
     * @ORM\Column(type="boolean")
     */
    private $activate;

    /**
     * @ORM\Column(type="array")
     */
    private $roles;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->token = uniqid();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getActivate(): ?bool
    {
        return $this->activate;
    }

    public function setActivate(bool $activate): self
    {
        $this->activate = $activate;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function __call($name, $arguments)
    {
        // TODO: Implement @method string getUserIdentifier()
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\TrickRepository;
use App\Repository\MediaRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     *
     * @param TrickRepository $trickRepository
     * @return Response
     */
    public function index(TrickRepository $trickRepository): Response
    {
        $tricks = $trickRepository->findAll();

        return $this->render('home/homepage.html.twig', [
            'tricks' => $tricks
        ]);
    }

    /**
     * Display the single trick page with trick data and the add comment form
     *
     * @Route("/trick/{id}", name="trick_show")
     *
     * @param Trick $trick
     * @param MediaRepository $mediaRepository
     * @param CommentRepository $commentRepository
     * @param Request $request
     * @param EntityManagerInterface $manager
     *
     * @return Response
     * @throws \Exception
     */
    public function show(Trick $trick, MediaRepository $mediaRepository, CommentRepository $commentRepository, Request $request, EntityManagerInterface $manager): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new \DateTime())
                ->setTrick($trick)
                ->setUser($this->getUser());
            $manager->persist($comment);
            $manager->flush();
            return $this->redirectToRoute('trick_show', ['id' => $trick->getId(), '_fragment' => $comment->getId()]);
        }
        $medias = $mediaRepository->findBy(['trick' => $trick->getId()]);
        $comments = $commentRepository->findBy(['trick' => $trick->getId()]);
        return $this->render('home/show.html.twig', [
            'trick' => $trick,
            'medias' => $medias,
            'comments' => $comments,
            'form' => $form->createView(),
        ]);
    }
}

templates/home/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snowtricks Homepage{% endblock %}

{% block body %}
    <!-- Start Home Image -->
    <div class="w-100 h-100">
        <div class="home-background">
            <div class="container">
                <span class="slogan"><p class="slogan-p">Welcome Snowboarder !</p></span>
            </div>
            <a href="#tricks"><i class="fas fa-chevron-down fa-4x chevron-down"></i></a>
        </div>
    </div>

    <!-- Start Tricks -->
    <span class="tricks-homepage" id="tricks"></span>
    <div class="container p-5">
        <div class="row">
            {% if tricks|length > 0 %}
                {% for trick in tricks %}
                    <div class="col-lg-4 mb-4 trick">
                        <div class="card">
                            <a href="{{ path('trick_show', {'id': trick.id}) }}"><img class="card-img-top home"
                                                                                      src="/images/"
                                                                                      alt="Trick"></a>
                            <div class="card-body test">
                                <a class="btn btn-outline-info btn-sm trick-link"
                                   href="{{ path('trick_show', {'id': trick.id}) }}"
                                   target="_blank">{{ trick.title }}</a>
                                {% if (app.user) and ((app.user.id == trick.user.id) or is_granted('ROLE_ADMIN')) %}
                                    <a class="float-right change-link ml-3 mr-3 pt-2"
                                       href="{{ path('trick_edit', {'id': trick.id}) }}" target="_blank"><i
                                                class="fas fa-pen fa-2x"></i></a>
                                    <a class="float-right change-link ml-2 pt-2" data-toggle="modal"
                                       data-target="#deleteTrickModal"
                                       data-href="{{ path('trick_delete', {'id': trick.id}) }}"><i
                                                class="fas fa-trash-alt fa-2x text-info"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="container">
                <div class="row justify-content-center m-3">
                    <a href="#" id="loadMoreTrick"><i class="fas fa-plus-circle fa-3x"></i></a>
                    <a href="#" id="loadLessTrick"><i class="fas fa-minus-circle fa-3x"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid relative">
        <a href="#tricks">
            <i class="fas fa-chevron-up fa-4x chevron-up"></i>
        </a>
    </div>
{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SnowTricks - {{ trick.title }}{% endblock %}

{% block body %}
    <!-- Start Trick -->
    <div class="container mt-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-10 col-md-offset-1 mt-5 mb-4">
                <div class="card mt-5">
                    <img class="card-img-top" src="/images/{{ trick.media }}" alt="{{ trick.title }}-main">
                    <div class="card-body">
                        <ul class="list-inline trick-data">
                            <li class="list-inline-item">
                                Par : <a target="_blank"
                                         href="{{ path('user_profile', { 'id' : trick.user.id }) }}">{{ trick.user.username }}</a>
                            </li>
                            |
                            <li class="list-inline-item">
                                Ajouté le {{ trick.createdAt | date('d/m/Y') }} (<small>Mise à jour le
                                    : {% if trick.updatedAt is defined %}{{ trick.updatedAt | date('d/m/Y') }}{% endif %}</small>)
                            </li>
                            |
                            <li class="list-inline-item">
                                Catégorie : {{ trick.category.label }}
                            </li>
                            |
                            <li class="list-inline-item">
                                <a href="#comments-block">{{ trick.comments | length }} commentaires</a>
                            </li>
                        </ul>
                        <hr>
                        <h4 class="card-title"><strong>{{ trick.title }}</strong></h4>
                        <p class="card-text">{{ trick.content }}</p>
                        <hr>
                        <!-- Start Carousel -->
                        {% if (media) %}
                            <div class="row d-none d-lg-flex load-media">
                                <div class="col-lg-6 col-md-12">
                                    <div id="carousel" class="carousel slide mt-3 mb-2" data-ride="carousel">
                                        <ol class="carousel-indicators">
                                            {% for media in medias %}
                                                <li data-target=".carousel"
                                                    data-slide-to="{{ loop.index0 }}" {% if loop.index0 == 0 %} class="active" {% endif %}></li>
                                            {% endfor %}
                                        </ol>
                                        <div class="carousel-inner enlarge">
                                            {% for media in medias %}
                                                <div class="carousel-item {% if loop.index0 == 0 %} active {% endif %}">
                                                    <img class="d-block" src="/images/{{ media.label }}"
                                                         alt="{{ trick.title }}-image-{{ media.id }}">
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <!-- Carousel navigation-->
                                        <a class="carousel-control-prev" href="#carousel" data-slide="prev">
                                            <span class="carousel-control-prev-icon"></span>
                                        </a>
                                        <a class="carousel-control-next" href="#carousel" data-slide="next">
                                            <span class="carousel-control-next-icon"></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <a href="#" id="loadMedia" class="d-md-block d-lg-none">
                                    <button class="btn btn-outline-secondary">Afficher les médias</button>
                                </a>
                                <a href="#" id="hideMedia" class="d-none d-md-none d-lg-none">
                                    <button class="btn btn-outline-secondary mt-3">Masquer les médias</button>
                                </a>
                            </div>
                        {% else %}
                            <div class="row justify-content-center">
                                <div class="d-inline-block text-center no-medias">
                                    <p class="mt-3 ml-3 mr-3">Pas de médias pour ce trick</p>
                                </div>
                            </div>
                        {% endif %}
                        <!-- End Carousel -->
                        <hr>
                        <h5 class="card-title">Description</h5>
                        <p class="card-text text-justify">{{ trick.content }}</p>
                    </div>
                </div>
                <!-- Start Comments -->
                <span class="comments-anchor" id="comments-block"></span>
                <div class="col-md-12 pl-0 pr-0">
                    <div class="comments text-left padDiv mb-30">
                        <div class="entry-comments">
                            <h6 class="mb-30">{{ trick.comments | length }} commentaires</h6>
                            <ul class="entry-comments-list list-unstyled">
                                {% for comment in comments %}
                                    <span class="comment-anchor" id="{{ comment.id }}"></span>
                                    <li>
                                        <div class="entry-comments-item">
                                            <div class="entry-comments-body">
                                                <span class="entry-comments-author"><a
                                                            href="{{ path('user_profile', { 'id' : comment.user.id }) }}"
                                                            target="_blank">{{ comment.user.username }}</a></span>
                                                <span class="comment-date">le {{ comment.createdAt | date('d/m/Y') }} à {{ comment.createdAt | date('H:i') }}</span>
                                                <p class="comment-content text-justify">{{ comment.content }}</p>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Comments -->
            </div>
        </div>
    </div>
{% endblock %}